<?php

namespace westonwatson\RealTag\Tests;


use PHPUnit\Framework\TestCase;
use westonwatson\realtag\CurlRequest;
use westonwatson\realtag\HttpRequest;
use westonwatson\realtag\RealTag;
use stdClass;

/**
 * Class RealTagTest
 *
 * @package westonwatson\realtag
 */
class RealTagTest extends TestCase
{
    const TEST_TOKEN     = 'ThisIsATestTokenString';

    const TEST_HEADERS   = ['Content-Type: application/json'];

    const GOOD_POST_DATA = [
        "FullName"     => "Donald Trump",
        "AddressLine1" => "1600 Pennsylvania Ave., NW",
        "City"         => "Washington",
        "State"        => "DC",
        "Zip"          => "20500",
        "ExternalID"   => "maga20500",
    ];

    const BAD_POST_DATA  = [];

    /**
     * @var
     */
    private $testResponse;

    /**
     * @var
     */
    private $testDecodedResp;

    /**
     *
     */
    public function setUp(): void
    {
        //require_once('../src/RealTag.php');
        require_once __DIR__ . '/../vendor/autoload.php';
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->testResponse    = json_encode(['test' => 'response']);
        $this->testDecodedResp = json_decode($this->testResponse);
    }

    public function testDecodeResponseAndSetEndpointAndSetHeaders()
    {
        $testTokenString = self::TEST_TOKEN;
        $testBaseUrl     = 'http://google.com';
        $testEndpoint    = "{$testBaseUrl}?code={$testTokenString}";

        $stub            = $this->createMock(CurlRequest::class);

        $stub
            ->expects($this->any())
            ->method('setUrl')
            ->with($testEndpoint);

        $stub
            ->expects($this->once())
            ->method('setHeaders')
            ->with(self::TEST_HEADERS);

        $stub
            ->expects($this->any())
            ->method('execute')
            ->willReturn($this->testResponse);

        $realtag = new RealTag($testTokenString, true, $stub);
        $realtag->setEndpoint($testBaseUrl);

        $mockedResponse = $realtag->call(self::GOOD_POST_DATA);

        $this->assertEquals($this->testDecodedResp, $mockedResponse);
    }
}
